# Generated by Django 2.1.5 on 2019-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiticle', '0005_article_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='char_count',
            field=models.IntegerField(default=10000),
        ),
    ]
